sufficient_loss: 0.0008
ddim_steps: 30
ddim_eta: 0.
optimization:
  opt_iters: 20
  log_every: 1
  lr: 0.01
  N_tokens: 10
  batch_size:  8
  uncond_guidance_scale: 1.

path2save_prefix: './results/experiments/inversion/'
shape: [4,64,64]
f: 8
device: 'cuda:0'
save_reconstruction: False