sufficient_loss: 0.0008
ddim_steps: 10
ddim_eta: 0.
optimization:
  opt_iters: 10
  log_every: 1
  lr: 1
  batch_size:  8
  uncond_guidance_scale: 1.

uncond_guidance_scale: 1.
path2save_prefix: './results/experiments/inversion/'
shape: [4,64,64]
device: 'cuda:0'
batch_size:  1
f: 8
save_reconstruction: True